class Env:
    SYSTEM = "SYSTEM"
    MONGO_URI = "MONGO_URI"
    MONGO_DB = "MONGO_DB"
    START_TIME = "START_TIME"
    END_TIME = "END_TIME"
    TIME_FRAME = "TIME_FRAME"
    EMAIL_ADDRESS = "EMAIL_ADDRESS"
    EMAIL_PASSWORD = "EMAIL_PASSWORD"
    EMAIL_RECIPIENTS = "EMAIL_RECIPIENTS"
    KITE_2FA_SECRET = "KITE_2FA_SECRET"
    SEND_EMAIL = "SEND_EMAIL"
    ENTRY_TIME_FRAME = "ENTRY_TIME_FRAME"
    EXIT_TIME_FRAME = "EXIT_TIME_FRAME"
    GOOGLE_SHEET_PRIVATE_KEY = 'GOOGLE_SHEET_PRIVATE_KEY'
    GOOGLE_SHEET_PRIVATE_KEY_ID = 'GOOGLE_SHEET_PRIVATE_KEY_ID'
    GOOGLE_SHEET = 'GOOGLE_SHEET'
    SERVICE_ACCOUNT = 'SERVICE_ACCOUNT'
    CLIENT_ID = 'CLIENT_ID'


class LogType:
    INFO = "INFO"
    ERROR = "ERROR"
    FAIL = "FAIL"
    SUCCESS = "SUCCESS"
    TRADE = "TRADE"
