class Env:
    SYSTEM = "SYSTEM"
    MONGO_URI = "MONGO_URI"
    MONGO_DB = "MONGO_DB"
    EMAIL_ADDRESS = "EMAIL_ADDRESS"
    EMAIL_PASSWORD = "EMAIL_PASSWORD"
    EMAIL_RECIPIENTS = "EMAIL_RECIPIENTS"
    GOOGLE_SHEET_PRIVATE_KEY = "GOOGLE_SHEET_PRIVATE_KEY"
    GOOGLE_SHEET_PRIVATE_KEY_ID = "GOOGLE_SHEET_PRIVATE_KEY_ID"
    GOOGLE_SHEET = "GOOGLE_SHEET"
    SERVICE_ACCOUNT = "SERVICE_ACCOUNT"
    CLIENT_ID = "CLIENT_ID"


class LogType:
    INFO = "INFO"
    ERROR = "ERROR"
    FAIL = "FAIL"
    SUCCESS = "SUCCESS"
    TRADE = "TRADE"


class SheetIndex:
    USER = 0
    ENVIRON = 1
