HOLIDAYS = [
    {
        "Day": "Monday",
        "Date": "22 Jan 2024",
        "Holiday": "Holiday declared under Negotiable Instrument Act",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Friday",
        "Date": "26 Jan 2024",
        "Holiday": "Republic Day",
        "Exchanges": ["nse", "bse", "mcx"],
    },
    {
        "Day": "Friday",
        "Date": "08 Mar 2024",
        "Holiday": "Maha Shivaratri",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Monday",
        "Date": "25 Mar 2024",
        "Holiday": "Holi",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Friday",
        "Date": "29 Mar 2024",
        "Holiday": "Good Friday",
        "Exchanges": ["nse", "bse", "mcx"],
    },
    {
        "Day": "Thursday",
        "Date": "11 Apr 2024",
        "Holiday": "Eid-Ul-Fitr (Ramzan Eid)",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Wednesday",
        "Date": "17 Apr 2024",
        "Holiday": "Ram Navami",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Wednesday",
        "Date": "01 May 2024",
        "Holiday": "Maharashtra Day",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Monday",
        "Date": "20 May 2024",
        "Holiday": "Parliamentary Elections",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Monday",
        "Date": "17 Jun 2024",
        "Holiday": "Bakri Eid",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Wednesday",
        "Date": "17 Jul 2024",
        "Holiday": "Moharram",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Thursday",
        "Date": "15 Aug 2024",
        "Holiday": "Independence Day",
        "Exchanges": ["nse", "bse", "mcx"],
    },
    {
        "Day": "Wednesday",
        "Date": "02 Oct 2024",
        "Holiday": "Mahatma Gandhi Jayanti",
        "Exchanges": ["nse", "bse", "mcx"],
    },
    {
        "Day": "Friday",
        "Date": "01 Nov 2024",
        "Holiday": "Diwali-Laxmi Pujan*",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Friday",
        "Date": "15 Nov 2024",
        "Holiday": "Gurunanak Jayanti",
        "Exchanges": ["nse", "bse"],
    },
    {
        "Day": "Wednesday",
        "Date": "25 Dec 2024",
        "Holiday": "Christmas",
        "Exchanges": ["nse", "bse", "mcx"],
    },
]
